version: '3.8'

services:
  client:
    image: phianhdev/my-personal-blog:latest
    container_name: Blog-FE
    build: .
    ports:
      - 3001:80
    networks:
      - my_network
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.users: admin

  nginx:
    container_name: Blog-Nginx-Client
    build: ./nginx

    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.users: admin
    depends_on:
      - client

my_network:
  external: true
